export const trafficCameraMapping = {
  '1111': { highway: 'TPE', description: 'TPE(PIE) - Exit 2 to Loyang Ave' },
  '1112': { highway: 'TPE', description: 'TPE(PIE) - Tampines Viaduct' },
  '1113': {
    highway: 'TPE',
    description: 'Tanah Merah Coast Road towards Changi',
  },
  '1701': {
    highway: 'CTE',
    description: 'CTE (AYE) - Moulmein Flyover LP448F',
  },
  '1702': {
    highway: 'CTE',
    description: 'CTE (AYE) - Braddell Flyover LP274F',
  },
  '1703': {
    highway: 'CTE',
    description: "CTE (SLE) - Blk 22 St George's Road",
  },
  '1704': {
    highway: 'CTE',
    description: 'CTE (AYE) - Entrance from Chin Swee Road',
  },
  '1705': {
    highway: 'CTE',
    description: 'CTE (AYE) - Ang Mo Kio Ave 5 Flyover',
  },
  '1706': { highway: 'CTE', description: 'CTE (AYE) - Yio Chu Kang Flyover' },
  '1707': { highway: 'CTE', description: 'CTE (AYE) - Bukit Merah Flyover' },
  '1709': {
    highway: 'CTE',
    description: 'CTE (AYE) - Exit 6 to Bukit Timah Road',
  },
  '1711': { highway: 'CTE', description: 'CTE (AYE) - Ang Mo Kio Flyover' },
  '2701': { highway: 'BKE', description: 'Woodlands Causeway (Towards Johor)' },
  '2702': { highway: 'BKE', description: 'Woodlands Checkpoint' },
  '2703': { highway: 'BKE', description: 'BKE (PIE) - Chantek F/O' },
  '2704': {
    highway: 'BKE',
    description: 'BKE (Woodlands Checkpoint) - Woodlands F/O',
  },
  '2705': { highway: 'BKE', description: 'BKE (PIE) - Dairy Farm F/O' },
  '2706': {
    highway: 'BKE',
    description: 'Entrance from Mandai Rd (Towards Checkpoint)',
  },
  '2707': { highway: 'BKE', description: 'Exit 5 to KJE (towards PIE)' },
  '2708': { highway: 'BKE', description: 'Exit 5 to KJE (Towards Checkpoint)' },
  '3702': { highway: 'ECP', description: 'ECP (Changi) - Entrance from PIE' },
  '3704': { highway: 'ECP', description: 'ECP (Changi) - Entrance from KPE' },
  '3705': {
    highway: 'ECP',
    description: 'ECP (AYE) - Exit 2A to Changi Coast Road',
  },
  '3793': { highway: 'ECP', description: 'ECP (Changi) - Laguna Flyover' },
  '3795': { highway: 'ECP', description: 'ECP (City) - Marine Parade F/O' },
  '3796': { highway: 'ECP', description: 'ECP (Changi) - Tanjong Katong F/O' },
  '3797': { highway: 'ECP', description: 'ECP (City) - Tanjung Rhu' },
  '3798': {
    highway: 'ECP',
    description: 'ECP (Changi) - Benjamin Sheares Bridge',
  },
  '4701': { highway: 'AYE', description: 'AYE (City) - Alexander Road Exit' },
  '4702': { highway: 'AYE', description: 'AYE (Jurong) - Keppel Viaduct' },
  '4703': { highway: 'AYE', description: 'Tuas Second Link' },
  '4704': { highway: 'AYE', description: 'AYE (CTE) - Lower Delta Road F/O' },
  '4705': {
    highway: 'AYE',
    description: 'AYE (MCE) - Entrance from Yuan Ching Rd',
  },
  '4706': {
    highway: 'AYE',
    description: 'AYE (Jurong) - NUS Sch of Computing TID',
  },
  '4707': {
    highway: 'AYE',
    description: 'AYE (MCE) - Entrance from Jln Ahmad Ibrahim',
  },
  '4708': {
    highway: 'AYE',
    description: 'AYE (CTE) - ITE College West Dover TID',
  },
  '4709': { highway: 'AYE', description: 'Clementi Ave 6 Entrance' },
  '4710': { highway: 'AYE', description: 'AYE(Tuas) - Pandan Garden' },
  '4712': { highway: 'AYE', description: 'AYE(Tuas) - Tuas Ave 8 Exit' },
  '4713': { highway: 'AYE', description: 'Tuas Checkpoint' },
  '4714': { highway: 'AYE', description: 'AYE (Tuas) - Near West Coast Walk' },
  '4716': {
    highway: 'AYE',
    description: 'AYE (Tuas) - Entrance from Benoi Rd',
  },
  '4798': { highway: 'AYE', description: 'Sentosa Tower 1' },
  '4799': { highway: 'AYE', description: 'Sentosa Tower 2' },
  '5794': { highway: 'PIE', description: 'PIEE (Jurong) - Bedok North' },
  '5795': { highway: 'PIE', description: 'PIEE (Jurong) - Eunos F/O' },
  '5797': { highway: 'PIE', description: 'PIEE (Jurong) - Paya Lebar F/O' },
  '5798': {
    highway: 'PIE',
    description: 'PIEE (Jurong) - Kallang Sims Drive Blk 62',
  },
  '5799': { highway: 'PIE', description: 'PIEE (Changi) - Woodsville F/O' },
  '6701': {
    highway: 'PIE',
    description: 'PIEW (Changi) - Blk 65A Jln Tenteram, Kim Keat',
  },
  '6703': {
    highway: 'PIE',
    description: 'PIEW (Changi) - Blk 173 Toa Payoh Lorong 1',
  },
  '6704': { highway: 'PIE', description: 'PIEW (Jurong) - Mt Pleasant F/O' },
  '6705': {
    highway: 'PIE',
    description: 'PIEW (Changi) - Adam F/O Special pole',
  },
  '6706': { highway: 'PIE', description: 'PIEW (Changi) - BKE' },
  '6708': { highway: 'PIE', description: 'Nanyang Flyover (Towards Changi)' },
  '6710': {
    highway: 'PIE',
    description: 'Entrance from Jln Anak Bukit (Towards Changi)',
  },
  '6711': { highway: 'PIE', description: 'Entrance from ECP (Towards Jurong)' },
  '6712': { highway: 'PIE', description: 'Exit 27 to Clementi Ave 6' },
  '6713': {
    highway: 'PIE',
    description: 'Entrance From Simei Ave (Towards Jurong)',
  },
  '6714': { highway: 'PIE', description: 'Exit 35 to KJE (Towards Changi)' },
  '6715': { highway: 'PIE', description: 'Hong Kah Flyover (Towards Jurong)' },
  '6716': { highway: 'PIE', description: 'AYE Flyover' },
  '7791': { highway: 'TPE', description: 'TPE (PIE) - Upper Changi F/O' },
  '7793': {
    highway: 'TPE',
    description: 'TPE(PIE) - Entrance to PIE from Tampines Ave 10',
  },
  '7794': { highway: 'TPE', description: 'TPE(SLE) - TPE Exit KPE' },
  '7795': {
    highway: 'TPE',
    description: 'TPE(PIE) - Entrance from Tampines FO',
  },
  '7796': {
    highway: 'TPE',
    description: 'TPE(SLE) - On rooflp of Blk 189A Rivervale Drive 9',
  },
  '7797': { highway: 'TPE', description: 'TPE(PIE) - Seletar Flyover' },
  '7798': { highway: 'TPE', description: 'TPE(SLE) - LP790F (On SLE Flyover)' },
  '8701': {
    highway: 'KJE',
    description: 'KJE (PIE) - Choa Chu Kang West Flyover',
  },
  '8702': { highway: 'KJE', description: 'KJE (BKE) - Exit To BKE' },
  '8704': {
    highway: 'KJE',
    description: 'KJE (BKE) - Entrance From Choa Chu Kang Dr',
  },
  '8706': { highway: 'KJE', description: 'KJE (BKE) - Tengah Flyover' },
  '9701': { highway: 'SLE', description: 'SLE (TPE) - Lentor F/O' },
  '9702': { highway: 'SLE', description: 'SLE(TPE) - Thomson Flyover' },
  '9703': {
    highway: 'SLE',
    description: 'SLE(Woodlands) - Woodlands South Flyover',
  },
  '9704': { highway: 'SLE', description: 'SLE(TPE) - Ulu Sembawang Flyover' },
  '9705': {
    highway: 'SLE',
    description: 'SLE(TPE) - Beside Slip Road From Woodland Ave 2',
  },
  '9706': {
    highway: 'SLE',
    description: 'SLE(Woodlands) - Mandai Lake Flyover',
  },
} as const;
